services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: skillset
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - skillset-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skillset"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma db seed && npm run dev -- --hostname 0.0.0.0"
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - skillset-node-modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  skillset-db-data:
  skillset-node-modules:
